show tables;
describe mytable;
select*
from mytable
limit 20;

-- 	Q1. WHAT IS THE TOTAL NO OF REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?
alter table mytable
change column `purchase_amount_(usd)`  purchase_amount bigint
;
select gender , sum(purchase_amount) as revenue
from mytable
group by gender;

-- Q2. WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE

select customer_id,purchase_amount
from mytable
where discount_applied = "Yes" and purchase_amount>= (select avg(purchase_amount) from mytable);

-- Q3. WHICH ARE THE TOP 5 PRODUCTS WITH HIGHEST AVERAGE REVIEW RATING

select item_purchased,round(avg(review_rating),2) as avg_pro_rating
from mytable
group by item_purchased
order by avg(review_rating) desc 
limit 5
;
-- Q4. COMPARE THE AVG PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING?
select shipping_type ,
round(avg(purchase_amount),2) as avg_purchase_amt
from mytable
where shipping_type in ("Standard" ,"Express")
group by shipping_type;

-- Q5. DO SUBSCRIBED CUSTOMERS SPEND MORE ? COMPARE AVG SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON SUBSCRIBERS?

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from mytable
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6. WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED? imp question

SELECT item_purchased,
round(100*sum(case when discount_applied= 'Yes' then 1 else 0 end )
/count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;


-- Q7 SEGMENT CUSTOMERS INTO NEW, RETURNING AND LOYAL BASED ON THEIR TOAL NUMBER OF PREVIOUS PURCHASES AND SHOW THE COUNT OF EACH SEGMENT

with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'NEW'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
from mytable
)
    
select customer_segment, count(*) as 'Number of Customers'   
from customer_type
group by customer_segment;


-- Q8. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY

with item_counts as (
select category,item_purchased,count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id)desc) as item_rank
from mytable
group by category,item_purchased
)

select  item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3
;

-- Q9. ARE CUSTOMERS WHO ARE REPEAT BUYERS ARE LIKELY TO BE SUBSCRIBED?

SELECT subscription_status, count(customer_id)as repeat_buyers
from mytable
where previous_purchases >=5
group by subscription_status;

-- 	Q10. WHAT IS THE REVENUE CONTIBUTION OF EACH AGE GROUP?

SELECT age_group,sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;



select user,host,plugin
from mysql.user;
alter user 'root'@'localhost'
identified with mysql_native_password by 'YOUR_PASSWORD'
;
flush privileges